### PR TITLE
Fixed links to GitHub, Instagram, and the Blue Alliance, and title fix.

### PR DESCRIPTION
**Pull request by Horace-McCullough**
I changed "ROBORAIDERS?" to "ROBORAIDERS"

### CODE REVIEW

**Comment by Horace-McCullough** [comment]
I later changed "ROBORAIDERS" to "NATHAN HALE ROBORAIDERS"

**Comment by StubblyCamera52** [comment]
looks good to me

**Comment by Horace-McCullough** [comment]
Changed titles eliminated all caps.

**Review by httphypixelnet — APPROVED** [review]
lgtm

**Pull request merged**
